package com.syj.domain;
// Generated 31-Jul-2016 20:50:50 by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Schoolstudent generated by hbm2java
 */
public class Schoolstudent implements java.io.Serializable {

	private int sid;
	private String sname;
	private String ssex;
	private String sdept;
	private Byte sage;
	private String saddress;
	private Set schoolchoices = new HashSet(0);

	public Schoolstudent() {
	}

	public Schoolstudent(int sid, String sname, String ssex, String sdept) {
		this.sid = sid;
		this.sname = sname;
		this.ssex = ssex;
		this.sdept = sdept;
	}

	public Schoolstudent(int sid, String sname, String ssex, String sdept, Byte sage, String saddress,
			Set schoolchoices) {
		this.sid = sid;
		this.sname = sname;
		this.ssex = ssex;
		this.sdept = sdept;
		this.sage = sage;
		this.saddress = saddress;
		this.schoolchoices = schoolchoices;
	}

	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public String getSsex() {
		return this.ssex;
	}

	public void setSsex(String ssex) {
		this.ssex = ssex;
	}

	public String getSdept() {
		return this.sdept;
	}

	public void setSdept(String sdept) {
		this.sdept = sdept;
	}

	public Byte getSage() {
		return this.sage;
	}

	public void setSage(Byte sage) {
		this.sage = sage;
	}

	public String getSaddress() {
		return this.saddress;
	}

	public void setSaddress(String saddress) {
		this.saddress = saddress;
	}

	public Set getSchoolchoices() {
		return this.schoolchoices;
	}

	public void setSchoolchoices(Set schoolchoices) {
		this.schoolchoices = schoolchoices;
	}

}
