package com.syj.domain;
// Generated 31-Jul-2016 20:50:50 by Hibernate Tools 5.1.0.Beta1

/**
 * Schoolchoice generated by hbm2java
 */
public class Schoolchoice implements java.io.Serializable {

	private Byte stuCourseId;
	private Schoolcourse schoolcourse;
	private Schoolstudent schoolstudent;
	private byte grade;

	public Schoolchoice() {
	}

	public Schoolchoice(byte grade) {
		this.grade = grade;
	}

	public Schoolchoice(Schoolcourse schoolcourse, Schoolstudent schoolstudent, byte grade) {
		this.schoolcourse = schoolcourse;
		this.schoolstudent = schoolstudent;
		this.grade = grade;
	}

	public Byte getStuCourseId() {
		return this.stuCourseId;
	}

	public void setStuCourseId(Byte stuCourseId) {
		this.stuCourseId = stuCourseId;
	}

	public Schoolcourse getSchoolcourse() {
		return this.schoolcourse;
	}

	public void setSchoolcourse(Schoolcourse schoolcourse) {
		this.schoolcourse = schoolcourse;
	}

	public Schoolstudent getSchoolstudent() {
		return this.schoolstudent;
	}

	public void setSchoolstudent(Schoolstudent schoolstudent) {
		this.schoolstudent = schoolstudent;
	}

	public byte getGrade() {
		return this.grade;
	}

	public void setGrade(byte grade) {
		this.grade = grade;
	}

}
