package com.syj.domain;
// Generated 31-Jul-2016 20:50:50 by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Schoolcourse generated by hbm2java
 */
public class Schoolcourse implements java.io.Serializable {

	private byte cid;
	private String cname;
	private Byte ccredit;
	private Set schoolchoices = new HashSet(0);

	public Schoolcourse() {
	}

	public Schoolcourse(byte cid, String cname) {
		this.cid = cid;
		this.cname = cname;
	}

	public Schoolcourse(byte cid, String cname, Byte ccredit, Set schoolchoices) {
		this.cid = cid;
		this.cname = cname;
		this.ccredit = ccredit;
		this.schoolchoices = schoolchoices;
	}

	public byte getCid() {
		return this.cid;
	}

	public void setCid(byte cid) {
		this.cid = cid;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public Byte getCcredit() {
		return this.ccredit;
	}

	public void setCcredit(Byte ccredit) {
		this.ccredit = ccredit;
	}

	public Set getSchoolchoices() {
		return this.schoolchoices;
	}

	public void setSchoolchoices(Set schoolchoices) {
		this.schoolchoices = schoolchoices;
	}

}
