package com.syj.domain;
// Generated 03-Aug-2016 18:27:03 by Hibernate Tools 5.1.0.Beta1

/**
 * Boarduser generated by hbm2java
 */
public class Boarduser implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private byte id;
	private String name;
	private String password;

	public Boarduser() {
	}

	public Boarduser(byte id, String name, String password) {
		this.id = id;
		this.name = name;
		this.password = password;
	}

	public byte getId() {
		return this.id;
	}

	public void setId(byte id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
