package com.syj.domain;
// Generated 03-Aug-2016 18:22:24 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * Boardinfo generated by hbm2java
 */
public class Boardinfo implements java.io.Serializable {

	private byte id;
	private String sender;
	private String receiver;
	private String content;
	private Date sendtime;
	private String attachment;

	public Boardinfo() {
	}

	public Boardinfo(byte id, String sender, String attachment) {
		this.id = id;
		this.sender = sender;
		this.attachment = attachment;
	}

	public Boardinfo(byte id, String sender, String receiver, String content, Date sendtime, String attachment) {
		this.id = id;
		this.sender = sender;
		this.receiver = receiver;
		this.content = content;
		this.sendtime = sendtime;
		this.attachment = attachment;
	}

	public byte getId() {
		return this.id;
	}

	public void setId(byte id) {
		this.id = id;
	}

	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	public String getReceiver() {
		return this.receiver;
	}

	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getSendtime() {
		return this.sendtime;
	}

	public void setSendtime(Date sendtime) {
		this.sendtime = sendtime;
	}

	public String getAttachment() {
		return this.attachment;
	}

	public void setAttachment(String attachment) {
		this.attachment = attachment;
	}

}
